stages:
  - validate
  - build

ruff_check:
  image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
  stage: validate
  script:
    - uv sync --all-groups
    - uv run ruff check .

ty_check:
  image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim
  stage: validate
  script:
    - uv sync --all-groups
    - uv run ty check .

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - Dockerfile
        - pyproject.toml
        - src/**/*
        - .gitlab-ci.yml
      when: always
    - when: never
