[project]
name = "ouranos-ml"
version = "0.1.0"
description = "Machine learning functionality for all Ouranos projects."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "accelerate>=1.12.0",
    "fastapi>=0.128.0",
    "fastapi-utils>=0.8.0",
    "lmstudio>=1.5.0",
    "matplotlib>=3.10.8",
    "numpy<2",
    "openai>=2.15.0",
    "optimum>=2.1.0",
    "pandas>=2.3.3",
    "pydantic-settings>=2.12.0",
    "scikit-learn>=1.8.0",
    "torch>=2.9.1",
    "transformers>=4.57.5",
    "uvicorn>=0.40.0",
]


[dependency-groups]
dev = ["commitizen>=4.13.10"]
linting = ["ruff>=0.14.13", "ty>=0.0.12"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128", marker = "sys_platform != 'darwin'" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[project.scripts]
start = "ouranos_ml.main:main"
ouranos_ml = "ouranos_ml.main:main"
experiment = "experiments.main:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    'F',      # Pyflakes
    'E',      # pycodestyle (Error)
    'I',      # isort
    'D',      # pydocstyle
    'UP',     # pyupgrade
    'YTT',    # flake8-2020
    'B',      # flake8-bugbear
    'T10',    # flake8-debugger
    'T20',    # flake8-print
    'C4',     # flake8-comprehensions
    'PERF',   # Perflint
    'PIE',    # flake8-pie
    'PYI006', # flake8-pyi
    'PYI062', # flake8-pyi
    'PYI063', # flake8-pyi
    'PYI066', # flake8-pyi
    'ANN',    # Type hinting
    "TID",    # flake8-tidy-imports
]
ignore = [
    'D100',
    'D104',
    'D105',
    'D107',
    'D205',
    'D415',
    'E501',
    'B011',
    'B028',
    'B904',
    'PIE804',
]
flake8-quotes = { inline-quotes = 'single', multiline-quotes = 'double' }
isort = { known-first-party = ['pydantic', 'tests'] }
mccabe = { max-complexity = 14 }
pydocstyle = { convention = 'google' }

[tool.ruff.format]
quote-style = 'double'

[tool.ruff.lint.extend-per-file-ignores]
"*/router.py" = ["F401", "E402"]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
