name: local
variables:
  - name: BASE_URL
    value: http://localhost:8005
  - name: MODEL
    value: hf.co/Qwen/Qwen2.5-Coder-3B-Instruct-GGUF:latest
  - name: EMBEDDING_MODEL
    value: hf.co/Qwen/Qwen3-Embedding-4B-GGUF:Q4_K_M
