from typing import Annotated, Any, Literal

from ouranos_ml.shared.domain.core.base_schema import BaseSchema
from pydantic import Discriminator, Field, Tag, TypeAdapter


class InputText(BaseSchema):
    """A text content part sent by the caller."""

    type: Literal["input_text"] = "input_text"
    text: str


class OutputText(BaseSchema):
    """A text content part generated by the model."""

    type: Literal["output_text"] = "output_text"
    text: str
    annotations: list[dict[str, Any]] = []


class InputImage(BaseSchema):
    """An image content part, given as a URL or base64 data URL (no Files API)."""

    type: Literal["input_image"] = "input_image"
    image_url: str
    detail: Literal["low", "high", "auto"] = "auto"


InputContent = Annotated[InputText | OutputText | InputImage, Field(discriminator="type")]


class InputMessage(BaseSchema):
    """A conversation message (replayed assistant output also parses as one; its ``id``/``status`` are ignored)."""

    type: Literal["message"] = "message"
    role: Literal["user", "assistant", "system", "developer"]
    content: str | list[InputContent]


class FunctionCall(BaseSchema):
    """A function tool call made by the model."""

    type: Literal["function_call"] = "function_call"
    call_id: str
    name: str
    arguments: str
    id: str | None = None
    status: Literal["in_progress", "completed", "incomplete"] | None = None


class FunctionCallOutput(BaseSchema):
    """The caller's result for a function tool call."""

    type: Literal["function_call_output"] = "function_call_output"
    call_id: str
    output: str


class SummaryText(BaseSchema):
    """A reasoning summary part."""

    type: Literal["summary_text"] = "summary_text"
    text: str


class Reasoning(BaseSchema):
    """The model's reasoning (Ollama puts the thinking text in ``encrypted_content``)."""

    type: Literal["reasoning"] = "reasoning"
    id: str
    summary: list[SummaryText] = []
    encrypted_content: str | None = None


def _input_item_type(value: object) -> str:
    """Discriminate input items by ``type``; an item with only a ``role`` is a message, as in the spec."""
    item_type = value.get("type") if isinstance(value, dict) else getattr(value, "type", None)
    return item_type or "message"


InputItem = Annotated[
    Annotated[InputMessage, Tag("message")]
    | Annotated[FunctionCall, Tag("function_call")]
    | Annotated[FunctionCallOutput, Tag("function_call_output")]
    | Annotated[Reasoning, Tag("reasoning")],
    Discriminator(
        _input_item_type,
        custom_error_type="invalid_value",
        custom_error_message="Unsupported input item type; expected one of 'message', 'function_call', "
        "'function_call_output', 'reasoning'",
    ),
]


class OutputMessage(BaseSchema):
    """An assistant message generated by the model."""

    type: Literal["message"] = "message"
    id: str
    role: Literal["assistant"] = "assistant"
    status: Literal["in_progress", "completed", "incomplete"]
    content: list[OutputText]


OutputItem = Annotated[OutputMessage | FunctionCall | Reasoning, Field(discriminator="type")]


class InputTokensDetails(BaseSchema):
    """Breakdown of input tokens."""

    cached_tokens: int = 0


class OutputTokensDetails(BaseSchema):
    """Breakdown of output tokens."""

    reasoning_tokens: int = 0


class Usage(BaseSchema):
    """Token usage for a response."""

    input_tokens: int
    output_tokens: int
    total_tokens: int
    input_tokens_details: InputTokensDetails = InputTokensDetails()
    output_tokens_details: OutputTokensDetails = OutputTokensDetails()


class FunctionTool(BaseSchema):
    """A function the model may call (the only tool type that runs against the LLM backend)."""

    type: Literal["function"] = "function"
    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = None
    strict: bool | None = None


class TextFormatText(BaseSchema):
    """Plain text output (the default)."""

    type: Literal["text"] = "text"


class TextFormatJSONSchema(BaseSchema):
    """Structured output conforming to a JSON Schema."""

    type: Literal["json_schema"]
    name: str
    json_schema: dict[str, Any] = Field(alias="schema")
    """The JSON Schema; uses the wire name ``schema`` (``BaseModel.schema`` is a deprecated classmethod)."""
    description: str | None = None
    strict: bool | None = None


class TextConfig(BaseSchema):
    """Text output configuration."""

    format: Annotated[TextFormatText | TextFormatJSONSchema, Field(discriminator="type")] = TextFormatText()


class ReasoningConfig(BaseSchema):
    """Reasoning configuration for thinking models."""

    effort: Literal["none", "minimal", "low", "medium", "high", "xhigh"] | None = None
    summary: Literal["auto", "concise", "detailed"] | None = None


class CreateResponseRequest(BaseSchema):
    """Request for ``POST /responses``, limited to the fields the LLM backend supports.

    Other OpenAI fields (``previous_response_id``, ``tool_choice``, ``store``, ...) are ignored,
    as the backend would ignore them.
    """

    model: str
    input: str | list[InputItem]
    instructions: str | None = None
    tools: list[FunctionTool] | None = None
    text: TextConfig | None = None
    reasoning: ReasoningConfig | None = None
    temperature: float | None = None
    top_p: float | None = None
    max_output_tokens: int | None = None
    stream: bool = False


class ResponseError(BaseSchema):
    """An error that caused a response to fail."""

    code: str
    message: str


class IncompleteDetails(BaseSchema):
    """Why a response is incomplete."""

    reason: str | None = None


class ResponseObject(BaseSchema):
    """A model response (the OpenAI ``response`` object)."""

    id: str
    object: Literal["response"] = "response"
    created_at: int
    completed_at: int | None = None
    status: Literal["completed", "failed", "in_progress", "cancelled", "queued", "incomplete"]
    model: str
    output: list[OutputItem]
    usage: Usage | None = None
    error: ResponseError | None = None
    incomplete_details: IncompleteDetails | None = None
    instructions: str | None = None
    tools: list[FunctionTool] = []
    text: TextConfig | None = None
    reasoning: ReasoningConfig | None = None
    temperature: float | None = None
    top_p: float | None = None
    max_output_tokens: int | None = None


class ResponseSnapshotEvent(BaseSchema):
    """A lifecycle event carrying the full response so far."""

    type: Literal["response.created", "response.in_progress", "response.completed", "response.failed"]
    sequence_number: int
    response: ResponseObject


class OutputItemEvent(BaseSchema):
    """An output item was added or completed."""

    type: Literal["response.output_item.added", "response.output_item.done"]
    sequence_number: int
    output_index: int
    item: OutputItem


class ContentPartEvent(BaseSchema):
    """A content part of a message was added or completed."""

    type: Literal["response.content_part.added", "response.content_part.done"]
    sequence_number: int
    item_id: str
    output_index: int
    content_index: int
    part: OutputText


class OutputTextDeltaEvent(BaseSchema):
    """A chunk of output text."""

    type: Literal["response.output_text.delta"]
    sequence_number: int
    item_id: str
    output_index: int
    content_index: int
    delta: str


class OutputTextDoneEvent(BaseSchema):
    """The finished output text of a content part."""

    type: Literal["response.output_text.done"]
    sequence_number: int
    item_id: str
    output_index: int
    content_index: int
    text: str


class FunctionCallArgumentsDeltaEvent(BaseSchema):
    """A chunk of function call arguments."""

    type: Literal["response.function_call_arguments.delta"]
    sequence_number: int
    item_id: str
    output_index: int
    delta: str


class FunctionCallArgumentsDoneEvent(BaseSchema):
    """The finished arguments of a function call."""

    type: Literal["response.function_call_arguments.done"]
    sequence_number: int
    item_id: str
    output_index: int
    arguments: str


class ReasoningSummaryTextDeltaEvent(BaseSchema):
    """A chunk of reasoning summary text."""

    type: Literal["response.reasoning_summary_text.delta"]
    sequence_number: int
    item_id: str
    output_index: int
    summary_index: int
    delta: str


class ReasoningSummaryTextDoneEvent(BaseSchema):
    """The finished text of a reasoning summary part."""

    type: Literal["response.reasoning_summary_text.done"]
    sequence_number: int
    item_id: str
    output_index: int
    summary_index: int
    text: str


class ErrorEvent(BaseSchema):
    """An error that ended the stream."""

    type: Literal["error"]
    sequence_number: int
    code: str | None = None
    message: str
    param: str | None = None


ResponseStreamEvent = Annotated[
    ResponseSnapshotEvent
    | OutputItemEvent
    | ContentPartEvent
    | OutputTextDeltaEvent
    | OutputTextDoneEvent
    | FunctionCallArgumentsDeltaEvent
    | FunctionCallArgumentsDoneEvent
    | ReasoningSummaryTextDeltaEvent
    | ReasoningSummaryTextDoneEvent
    | ErrorEvent,
    Field(discriminator="type"),
]

STREAM_EVENT_ADAPTER: TypeAdapter[ResponseStreamEvent] = TypeAdapter(ResponseStreamEvent)
